title: Amal Nigam # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="linkedin.com/in/amalnigam/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/amn326/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
